### ISSUE TITLE
vercel部署报错：Error: Not found "prefetch-page" dependency package

### ISSUE THREAD

**Issue by JIeJaitt** [Lete114/Hexo-prefetch#1]
```bash
Error: Not found "prefetch-page" dependency package
--
12:29:09.734 | at handler (/vercel/path0/node_modules/hexo-prefetch/index.js:26:11)
12:29:09.734 | at handler (/vercel/path0/node_modules/hexo-prefetch/index.js:24:14)
12:29:09.734 | at Hexo.<anonymous> (/vercel/path0/node_modules/hexo-prefetch/index.js:51:56)
12:29:09.735 | at Hexo.tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
12:29:09.735 | at Hexo.<anonymous> (/vercel/path0/node_modules/bluebird/js/release/method.js:15:34)
12:29:09.735 | at /vercel/path0/node_modules/hexo/lib/extend/filter.ts:88:52
12:29:09.735 | at tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
12:29:09.735 | at Object.gotValue (/vercel/path0/node_modules/bluebird/js/release/reduce.js:166:18)
12:29:09.736 | at Object.gotAccum (/vercel/path0/node_modules/bluebird/js/release/reduce.js:155:25)
12:29:09.736 | at Object.tryCatcher (/vercel/path0/node_modules/bluebird/js/release/util.js:16:23)
12:29:09.736 | at Promise._settlePromiseFromHandler (/vercel/path0/node_modules/bluebird/js/release/promise.js:547:31)
12:29:09.736 | at Promise._settlePromise (/vercel/path0/node_modules/bluebird/js/release/promise.js:604:18)
12:29:09.736 | at Promise._settlePromiseCtx (/vercel/path0/node_modules/bluebird/js/release/promise.js:641:10)
12:29:09.737 | at _drainQueueStep (/vercel/path0/node_modules/bluebird/js/release/async.js:97:12)
12:29:09.737 | at _drainQueue (/vercel/path0/node_modules/bluebird/js/release/async.js:86:9)
12:29:09.737 | at Async._drainQueues (/vercel/path0/node_modules/bluebird/js/release/async.js:102:5)
12:29:09.737 | at Immediate.Async.drainQueues [as _onImmediate] (/vercel/path0/node_modules/bluebird/js/release/async.js:15:14)
12:29:09.737 | at processImmediate (node:internal/timers:476:21)
12:29:09.863 | Error: Command "npm run build" exited with 2


```

**Comment by lete114** [comment]
bug已修复
